#!/usr/bin/env bash
set -euo pipefail

if [ $# -ne 2 ] && [ $# -ne 1 ]; then
        echo "Usage: $0 [WIM FILE] [WIM INDEX]"
        echo "or: $0 [SYSROOT PATH]"
        exit 1
fi

source ../common/afdko.bash

if [ $# -eq 2 ]; then
        wim_file="$1"
        wim_index="$2"

        umount mnt >/dev/null 2>&1 || true
        mkdir -p mnt

        wimmount "$wim_file" "$wim_index" mnt

        sysroot=mnt
elif [ $# -eq 1 ]; then
        sysroot="$1"
fi

"$afdko"/bin/otf2otc -o windowsfonts.ttc mnt/Windows/Fonts/*.?t?

if [ "x$sysroot" = xmnt ]; then
        umount mnt
        rmdir mnt
fi
