#!/usr/bin/env bash
set -euo pipefail

if [ $# -ne 2 ]; then
        echo "Usage: $0 [WIM FILE] [WIM INDEX]"
        exit 1
fi

if ! command -v python3 >/dev/null; then
        echo "python3 required"
        exit 1
fi

if ! [ -f afdko/installed ]; then
        echo "Installing AFDKO..."
        rm -rf afdko
        python3 -m venv afdko
        afdko/bin/pip install afdko
        touch afdko/installed
fi

wim_file="$1"
wim_index="$2"

mkdir -p mnt
umount mnt >/dev/null 2>&1 || true

wimmount "$wim_file" "$wim_index" mnt

afdko/bin/otf2otc -o windowsfonts.ttc mnt/Windows/Fonts/*.?t?

umount mnt
