#!/usr/bin/env bash
set -euo pipefail

if [ $# -ne 2 ]; then
        echo "Usage: $0 [WIM FILE] [WIM INDEX]"
        exit 1
fi

source ../common/afdko.bash

wim_file="$1"
wim_index="$2"

mkdir -p mnt
umount mnt >/dev/null 2>&1 || true

wimmount "$wim_file" "$wim_index" mnt

"$afdko"/bin/otf2otc -o windowsfonts.ttc mnt/Windows/Fonts/*.?t?

umount mnt
