#!/usr/bin/env bash
set -euo pipefail

if [ $# -ne 2 ] && [ $# -ne 1 ]; then
        echo "Usage: $0 [WIM FILE] [WIM INDEX]"
        exit 1
fi

source ../common/python.bash

wim_file="$1"
wim_index="$2"

rm -rf fonts

wimextract "$wim_file" "$wim_index" '/Windows/Fonts/*.?t?' --dest-dir=fonts

mkfontscale fonts
mkfontdir fonts
